[template]
prefix = "/nginxproxy/websites/site1"
keys = [ 
    "domain",
    "upstream",
    "ipandport", 
]
owner       = "nginx"
mode        = "0644"
src         = "nginx.tmpl"
dest        = "/etc/nginx/sites-enabled/site1"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "service nginx reload"
